### ISSUE TITLE
Provide API for MAU

### ISSUE THREAD

**Issue by syntrydy** [JanssenProject/jans-config-api#35]
### User Story Title.

Administrators need a way to check monthly active users. To accomplish that, the UI team needs an API that can provide such information.

### User Story Meta Information.

Administrators should be able to request active users per day, month, year, or any data range.

#### Risk Level. 

This allows us to assign a risk level to the user story, which represents the level of uncertainty around its completion. Also graded from 1 (Low risk) to 5 (Very High Risk)

#### Effort.

 This allows us to assign how much work needs to be done to get a user story complete. This will be an integer to be designated by the development team.

#### Priority.

MEDIUM.

### Description.
Administrators need a way to check monthly active users. To accomplish that, the UI team needs an API that can provide such information.

### Notes. 
Additional important information can be placed here. Links, references, etc.

**Comment by yuriyz** [comment]
oxauth related ticket https://github.com/GluuFederation/oxAuth/issues/1512#issuecomment-768926617

**Comment by pujavs** [comment]
Functionality for user stats added -> /jans-config-api/api/v1/stat
Sample response: 
 "response": {
    "202107": {
      "token_count_per_granttype": {
        "client_credentials": {
          "access_token": 66
        }
      },
      "monthly_active_users": 0
    }
  }

Test Report: 
[src.test.resources.feature.stat.stat.pdf](https://github.com/JanssenProject/jans-config-api/files/6870263/src.test.resources.feature.stat.stat.pdf)

**Comment by yuriyz** [comment]
@pujavs implementation has to be updated following Mike's feedback https://github.com/GluuFederation/oxAuth/issues/1554#issuecomment-885755267

**Comment by pujavs** [comment]
Implemented change to use the **'jans_stat'**

[Uploading src.test.resources.feature.stat.stat_2.pdf…]()

![image](https://user-images.githubusercontent.com/43700552/126961926-1dccea4a-6caf-4fee-a180-70bd29bf521b.png)

**Comment by pujavs** [comment]
Reopening the issue as access-token generated via external IDP by admin-ui is not recognized/validated by jans-auth IDP
Reference to admin-ui architecture : https://github.com/GluuFederation/gluu-admin-ui/wiki/Janssen-Admin-UI----Application-Architecture#generating-api-protection-token-at2-and-enablingdisabling-features-at-frontend

**Comment by pujavs** [comment]
Options analyzed:
**Option#1:** jans-auth also supports external issuer
**Option#2:** Do away with jans_stat and jans-conf-api authorizes user against jans-config-scope for /stats endpoint like https://jans.io/oauth/config/stats.readonly
**Option#3:** Keeping jans_stat transparent to the caller of jans-config-api. In this the internal client of jans-config-api will have to have the jans-statscope. Client will have to call pass token with https://jans.io/oauth/config/stats.readonly scope and jans-config-api will authorize it. If successful then jans-config-api will use its internal client to create a new token with the required scope and invoke jans-auth with it.

**Comment by pujavs** [comment]
Summarizing the changes done,
1) jans-confi-api DB config to maintain exclusiveAuthScopes, which is list of auth specific scopes that will be used to generate access token. As of now only one value jans_stat -> “exclusiveAuthScopes”: [“jans_stat”]
2) This value will be read on application startup
3) Jans Config-api endpoint to specify all required scopes that is jans-config-api as well as auth specific
Example: StatResource
@GET
@ProtectedApi(scopes = { “https://jans.io/oauth/config/stats.readonly", “jans_stat” })
4) On receipt of access token jans-config-api will introspect the access token and for validating the scopes
4.1) If the endpoint needs auth specific token and if the introspected token has it along with all required scopes then the call will be authorized
4.2) Else if auth specific scope is missing then jans-config-api will use its internal client to generate a new access token with all required scopes along with auth specific scope. Followed by Introspection and authorization if valid.

**Code merged to master**

**Comment by pujavs** [comment]
![Stat_Endpoint_JWT_Testing](https://user-images.githubusercontent.com/43700552/131496199-c31ee987-f957-4282-bfa5-be0c687b14a0.png)

**Comment by pujavs** [comment]
Changes done to remove "response" key based on user request.

![image](https://user-images.githubusercontent.com/43700552/132248569-b3818ef0-0fb8-4842-9ff6-58632079bf5a.png)

**Comment by pujavs** [comment]
Request to add granular details for “access_token” like token Types, grants & responseType
