### ISSUE TITLE
How to bootstrap the first client to call the config-api

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-config-api#4]
As the jans-config-api is protected by default, on install, calls to the API return `401 - Unauthorized`
  
How do you configure the auth-server, client and client creds that the config API's relies on for authorization.

**Comment by yuriyz** [comment]
Client is created by installation script. So it's pre-configured.

**Comment by mbaser** [comment]
You can see client and secret for config api in `setup.properties.last`. Client for config api has prefix `1801.`

**Comment by ruiengana** [comment]
Where exactly can I find client and secret for config api in "setup.properties.last"?

**Comment by mbaser** [comment]
Please open a ticket at https://support.gluu.org/
This is not a place for your questions.

**Comment by yuriyz** [comment]
Closing since it seems to be answered.

**Comment by moabu** [comment]
Hey @ruiengana I am closing this issue in favor of this https://github.com/JanssenProject/docker-jans-config-api/issues/5. We will address it asap.
