### ISSUE TITLE
Provide a set of endpoints for user management

### ISSUE THREAD

**Issue by syntrydy** [JanssenProject/jans-config-api#50]
### User Story Title.

Implement endpoints for user management

### User Story Meta Information.

This should be base on the existing SCIM project

#### Priority.

 MEDIUM

### Description.

As an API consumer with the user management permission set, I should be able to: 
 
- List all users
- Search for users base on a search pattern
- Add new user
- Update existing user
- Remove a user 
-  Activate/Deactivate a user
- Manage user password:
            1. Password policy:  define the password complexity(eg. min length, 
            2. Password Reset: reset my password
            3. Username Recovery

**Comment by pujavs** [comment]
Implemented endpoints for User Management.
Regarding, **Manage user password** there is nothing specific in scim regarding password policy management.  This will need more decision on what should be the policy and best place to implement it. It will be good to create a sperate JIRA for the same with proper details to take fw.
