### ISSUE TITLE
Return Client Secret in Clear

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-config-api#7]
GET /clients is returning an encoded version of "clientSecret" rather than original value of "clientSecret".

According to REST principles, the output of a GET call should be usable in a subsequent PUT call, and if we do this without changing the "clientSecret", the secret gets messed up and client stop working.

**Comment by nynymike** [comment]
Encoded or hashed?

**Comment by ruiengana** [comment]
This isn't an hash, this is Base64 encoded of DES encrypted client secret.

**Comment by nynymike** [comment]
So it looks to me like the config API is returning the hash. I cannot base64 decode `V4sY+lpEkRnKIfBKzP5hxQ==`.   If the client_id is hashed before storage, it can't be sent back in clear.

**Comment by ruiengana** [comment]
> So it looks to me like the config API is returning the hash. I cannot base64 decode `V4sY+lpEkRnKIfBKzP5hxQ==`. If the client_id is hashed before storage, it can't be sent back in clear.

The API is returning the encrypted base64 encoded of secret, expectation is for API to return clear secret.
See below.

![image](https://user-images.githubusercontent.com/11096527/104159083-9908b400-53e6-11eb-85e5-25896b168753.png)

**Comment by ruiengana** [comment]
@nynymike ,can you help with this issue?

**Comment by pujavs** [comment]
Fixed and code checked in

![image](https://user-images.githubusercontent.com/43700552/105989852-b4064400-60c7-11eb-870c-c4e655843eca.png)

**Comment by ruiengana** [comment]
Great! Is this fix included in jans-config-api 1.0.0_dev docker image?

**Comment by iromli** [comment]
@ruiengana yes

![Screenshot from 2021-01-28 04-14-19](https://user-images.githubusercontent.com/231601/106055002-5f8eb300-611f-11eb-9dd3-cc7200ec1ecb.png)
